CREATE DATABASE IF NOT EXISTS eventpass_ai CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eventpass_ai;
CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,role_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,email VARCHAR(180) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,status VARCHAR(20) DEFAULT 'active',remember_token VARCHAR(120) NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,INDEX(role_id),FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE event_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,organizer_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED,title VARCHAR(180) NOT NULL,description TEXT,poster VARCHAR(255),address VARCHAR(255),venue VARCHAR(120),map_url VARCHAR(255),start_date DATE,end_date DATE,start_time TIME,end_time TIME,is_multiday TINYINT(1) DEFAULT 0,capacity INT DEFAULT 0,status VARCHAR(20) DEFAULT 'draft',visibility VARCHAR(20) DEFAULT 'public',is_paid TINYINT(1) DEFAULT 0,price DECIMAL(10,2) DEFAULT 0,ecm_enabled TINYINT(1) DEFAULT 0,ecm_credits INT DEFAULT 0,slug VARCHAR(191) UNIQUE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,INDEX(organizer_id),INDEX(category_id),FOREIGN KEY(organizer_id) REFERENCES users(id),FOREIGN KEY(category_id) REFERENCES event_categories(id));
CREATE TABLE participants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,first_name VARCHAR(100),last_name VARCHAR(100),email VARCHAR(180),phone VARCHAR(50),company VARCHAR(120),profession VARCHAR(120),notes TEXT,privacy_consent TINYINT(1) DEFAULT 0,payment_status VARCHAR(20) DEFAULT 'pending',checkin_status VARCHAR(20) DEFAULT 'not_checked',created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,INDEX(event_id),INDEX(email),FOREIGN KEY(event_id) REFERENCES events(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE tickets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,participant_id BIGINT UNSIGNED,event_id BIGINT UNSIGNED,type VARCHAR(50),price DECIMAL(10,2),ticket_code VARCHAR(120) UNIQUE,status VARCHAR(20),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(participant_id) REFERENCES participants(id),FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE qr_codes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,participant_id BIGINT UNSIGNED,event_id BIGINT UNSIGNED,token VARCHAR(191) UNIQUE,path VARCHAR(255),used_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(participant_id) REFERENCES participants(id),FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE checkins (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,participant_id BIGINT UNSIGNED,event_id BIGINT UNSIGNED,operator_id BIGINT UNSIGNED,status VARCHAR(20),checked_in_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(participant_id) REFERENCES participants(id),FOREIGN KEY(event_id) REFERENCES events(id),FOREIGN KEY(operator_id) REFERENCES users(id));
CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,participant_id BIGINT UNSIGNED,event_id BIGINT UNSIGNED,provider VARCHAR(20),amount DECIMAL(10,2),currency CHAR(3),status VARCHAR(20),transaction_id VARCHAR(191),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(participant_id) REFERENCES participants(id),FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE coupons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED,code VARCHAR(80) UNIQUE,discount_type VARCHAR(20),discount_value DECIMAL(10,2),max_uses INT,used_count INT DEFAULT 0,expires_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE sponsors (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(140),logo VARCHAR(255),banner VARCHAR(255),website VARCHAR(255),email VARCHAR(180),phone VARCHAR(50),description TEXT,plan VARCHAR(50),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE event_sponsors (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED,sponsor_id BIGINT UNSIGNED,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,UNIQUE(event_id,sponsor_id),FOREIGN KEY(event_id) REFERENCES events(id),FOREIGN KEY(sponsor_id) REFERENCES sponsors(id));
CREATE TABLE documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED,participant_id BIGINT UNSIGNED,type VARCHAR(80),path VARCHAR(255),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(event_id) REFERENCES events(id),FOREIGN KEY(participant_id) REFERENCES participants(id));
CREATE TABLE notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED,title VARCHAR(160),message TEXT,channel VARCHAR(50),sent_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED,type VARCHAR(50),path VARCHAR(255),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,`key` VARCHAR(120) UNIQUE,`value` TEXT,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED,action VARCHAR(140),entity VARCHAR(80),entity_id BIGINT UNSIGNED,ip_address VARCHAR(45),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE email_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE,subject VARCHAR(180),body_html LONGTEXT,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
INSERT INTO roles (id,name,created_at,updated_at) VALUES (1,'Super Admin',NOW(),NOW()),(2,'Organizzatore',NOW(),NOW()),(3,'Hostess',NOW(),NOW()),(4,'Partecipante',NOW(),NOW()),(5,'Sponsor',NOW(),NOW());
INSERT INTO users (role_id,name,email,password,status,created_at,updated_at) VALUES
(1,'Admin','admin@eventpass.ai','$2y$10$0Jf6CNQfDU7j7iMZ4LdB7.s3taFQ6RYxv2IG8g38gOb99aX9ySPx6','active',NOW(),NOW()),
(2,'Organizer','organizer@test.com','$2y$10$iTkIjf0D0kg5j4sfH8ewyuYf6Sglx2x4YW8e8u/ETx4xg6syL8WeW','active',NOW(),NOW()),
(3,'Hostess','hostess@test.com','$2y$10$0uW8u8H4G8OwJd4mpS2E6ecQ3XpgF8sSTmV8RnPeNPOB5pw39xypS','active',NOW(),NOW());
